### ISSUE TITLE
Question: how do you pass a document property?

### ISSUE THREAD

**Issue by chujanen** [TIBCOSoftware/spotfire-wrapper#49]
There can be "document properties" configured in a DXP file and I have seen mention of these properties being passed into the web player, but I do not see any mechanism to do so using this spotfire-wrapper component.

How do you pass them in?

**Comment by tbabik** [comment]
Hi,
I would also be interested in knowing how this can be done. The Javascript API seems to over a "setDocumentProperty" which can be used to change properties after a document is loaded.
But how to do it with the Wrapper? And can this be done upfront before loading the document first?
Thanks

**Comment by nicolasderoche** [comment]
Hello @chujanen and @tbabik.

Sorry for the late answer.
I looked into it and will provide a way to have access in read write mode to list of properties.

Kindly Regards
Nicolas

**Comment by nicolasderoche** [comment]
@chujanen , @tbabik : Just a note, version 0.12.0 now exposes SpotfireDocument, and you can get/list/set properties.
Enjoy!
